### ISSUE TITLE
TypeError: Gtk.IconTheme.get_default(...) is null

### ISSUE THREAD

**Issue by jnnkB** [2nv2u/gnome-shell-extension-syncthing-indicator#1] opened 2020-11-12 08:52 UTC
When I install this extensions I get the follow error message

```
 JS ERROR: Extension syncthing@gnome.2nv2u.com: TypeError: Gtk.IconTheme.get_default(...) is null
                                        init@~/.local/share/gnome-shell/extensions/syncthing@gnome.2nv2u.com/extension.js:436:16
                                        _callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:428:50
                                        loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:345:27
                                        _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:590:18
                                        collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
                                        _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:569:19
                                        _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:599:18
                                        _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:630:18
                                        init@resource:///org/gnome/shell/ui/extensionSystem.js:55:14
                                        _initializeUI@resource:///org/gnome/shell/ui/main.js:254:22
                                        start@resource:///org/gnome/shell/ui/main.js:143:5
```

```
$ gnome-shell --version
GNOME Shell 3.36.7
```

**Comment by glasl** [comment] 2020-12-29 11:47
Having the same issue

`$ gnome-shell --version
GNOME Shell 3.38.2`

**Comment by wbolster** [comment] 2021-02-26 21:33
i can confirm that the `Gtk.IconTheme` line:

- causes a crash on startup in wayland sessions
- can be safely commented out to make the extension work again. all icons show up just fine.

**Comment by 2nv2u** [comment] 2021-02-26 21:50
I'll see if the icons also still works in X itself and fix this, thanks for figuring this out! +1:

**Comment by 2nv2u** [comment] 2021-02-26 21:56
Fixed in next version!

**Closed by 2nv2u** 2021-02-26 21:56 UTC

**Comment by wbolster** [comment] 2021-02-26 21:58
awesome. since wayland sessions are the default on pretty much all modern distros (arch, fedora, …), you may want to upload a new version to extensions.gnome.org to make it work ‘out of the box’ again for everyone 🙏

thanks for working on this extension, btw. it's by far the simplest way to get syncthing up and running on a new machine, thanks to the menu and the auto-installed systemd unit. 🙇

**Comment by 2nv2u** [comment] 2021-02-27 10:20
Yes I did bump the version and uploaded it to the gnome extension page so it will be there soon. It's part of the release cycle. ;)
Great you like it! My goal is / was to make it as easy as possible, I will one day also spend some more time on making sure that all the non happy cases go smoothly too, but I'll always keep it simple and unobtrusive.
